Add affinity to Helm chart
aws/secrets-store-csi-driver-provider-aws pull request #237
Opened 2023-06-15 01:42 UTC by dongheeJeong

*Issue #, if available:*
Not available.

*Description of changes:*
Add affinity to Helm chart.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-06-26 18:41 UTC, goyalya commented
Thank you for submitting the request. Could you please elaborate on the need to add Affinity option ?

2023-07-03 09:27 UTC, dongheeJeong commented
@goyalya 

As EKS fargate does not support daemonset, affinity is required like [this](https://github.com/aws/amazon-vpc-cni-k8s/blob/85654cf9b02f7aed240fd5b2f43be19f47800109/config/master/aws-k8s-cni.yaml#L265-L268).

2023-07-03 18:52 UTC, simonmarty approved these changes

2023-07-10 18:59 UTC, danmancuso requested changes

2023-07-10 18:59 UTC, danmancuso commented on charts/secrets-store-csi-driver-provider-aws/templates/.daemonset.yaml.swp
Remove this .swp file before merging.

2023-07-10 19:05 UTC, danmancuso commented on charts/secrets-store-csi-driver-provider-aws/templates/.daemonset.yaml.swp
Removed.

2023-07-10 19:07 UTC, danmancuso approved these changes

2023-07-10 19:08 UTC, merged